export const REQUEST_TRAININGS = 'REQUEST_TRAININGS';
export const RECEIVE_TRAININGS = 'RECEIVE_TRAININGS';
export const INVALIDATE_TRAININGS = 'INVALIDATE_TRAININGS';
export const REQUEST_ONE_TRAINING = 'REQUEST_ONE_TRAINING';
export const RECEIVE_ONE_TRAINING = 'RECEIVE_ONE_TRAINING';
export const INVALIDATE_ONE_TRAINING = 'INVALIDATE_ONE_TRAINING';